#!/usr/bin/env bash

set -e
set -x

#docker_user="quay.io/rranshous"
docker_user="rranshous"
worker_image="rranshous/ffmpeg"
data_file_path=$1
data_file_abs_path=$(readlink -f $data_file_path)
data_dir=$(dirname $data_file_abs_path)
data_file=$(basename $data_file_abs_path)
data_file_encoded=$(echo "$data_file" | base64)
new_image_name="$docker_user/data-image-split-$(echo "%(data_file)" | md5sum | cut -d' ' -f1)"

echo "checking for existing worker image"
if [[ "$(docker images -q new_image_name 2> /dev/null)" == "" ]]; then
  echo "worker image not found"

  echo "pulling data container image"
  docker pull $worker_image
  
  echo "starting base container"
  cid=$(docker run -d --entrypoint=/bin/sleep $worker_image 360)
  
  echo "creating data dir in container"
  docker exec $cid mkdir /input_data
  
  echo "copying data to the container: $cid"
  docker cp "$data_file_path" "$cid:/input_data/$data_file"
  
  echo "creating new image as as $new_image_name"
  docker commit -m "added $data_file to /input_data/$data_file" $cid "$new_image_name"
  
  echo "killing container"
  docker kill $cid
  
  echo "stopping and removing temp container $cid"
  docker rm $cid
  
  #echo "uploading container to repository"
  #docker push "$new_image_name"
else
  echo "worker image found"
fi

echo "starting workers"
wcid=docker run -d --volumes-from=output-data $new_image_name -i /input_data/$data_file -ss 00:00:30.0 -c copy -t -vcodec copy -acodec copy 00:00:10.0 /data/$data_file-test
echo "worker started: $wcid"
